name: Generate Ansible Inventory

on:
  workflow_dispatch:

jobs:
  generate-inventory:
    runs-on: [ ansible-master ]

    steps:
     

      - name: Create inventory directory
        run: |
          sudo -u erwin mkdir -p /home/erwin/ansible/
          sudo chown -R erwin:erwin /home/erwin/ansible

      - name: Generate inventory.yaml
        run: |
          sudo -u erwin bash -c 'cat > /home/erwin/ansible/inventory.yaml' << 'EOF'
          ---
          all:
            children:
              ansible-master:
                hosts:
                  master:
                    ansible_host: 10.128.0.8
                    ansible_user: erwin
                    

              ansible-node1:
                hosts:
                  node1:
                    ansible_host: 10.166.0.2
                    ansible_user: erwin
                  
             ansible-node2:
                hosts:
                  node2:
                    ansible_host: 10.128.0.22
                    ansible_user: erwin      

              
          EOF
