name: Generate Ansible Inventory

on:
  workflow_dispatch:

jobs:
  generate-inventory:
    runs-on: [ ansible-master ]

    steps:
     

      - name: Create inventory directory
        run: |
          sudo -u erwin mkdir -p /home/erwin/ansible/
          sudo chown -R erwin:erwin /home/erwin/ansible

      - name: Generate inventory.yaml
        run: |
          sudo -u erwin bash -c 'cat > /home/erwin/ansible/inventory.yaml' << 'EOF'
          ---
          all:
            children:
              webservers:
                hosts:
                  web01:
                    ansible_host: 10.166.0.2
                    ansible_user: erwin
                    

              databases:
                hosts:
                  db01:
                    ansible_host: 10.128.0.22
                    ansible_user: erwin
                    db_version: 14
                   

              
          EOF
